In [2]:
import pandas as pd 
import numpy as np 
import re
from pathlib import Path
import os
from datetime import datetime

In [13]:
base_dir = Path(r'E:\文档\Python\Qingbaot\brand_top_store\result\pickle')

In [17]:
total_df_lst = []
for one_pkl in base_dir.iterdir():
    one_df = pd.read_excel(one_pkl)
    # print(type(one_df))
    # if type(one_df) != '':
    total_df_lst.append(one_df)

In [18]:
total_df = pd.concat(total_df_lst, sort=True)

In [19]:
total_df.head()

,Unnamed: 0,middle_clss,month,senior_name,shop_link,全选,地域,掌柜名,排名,销售额,销量
0,0,乳贴,201803,内衣家居服,http://shop112068244.taobao.com/,NaN,"辽宁省, 锦州市",柯恩纳旗舰店,1,1891576,47117
1,1,乳贴,201803,内衣家居服,http://shop191214021.taobao.com/,NaN,NaN,斯米莱旗舰店,2,1314520,34911
2,2,乳贴,201803,内衣家居服,http://shop66862794.taobao.com/,NaN,"浙江, 杭州",艾丝朵秀旗舰店,3,272175,21189
3,3,乳贴,201803,内衣家居服,http://shop110998652.taobao.com/,NaN,"湖北省, 武汉市",安黛拉旗舰店,4,607402,14688
4,4,乳贴,201803,内衣家居服,http://shop69194068.taobao.com/,NaN,上海,jeeanjoose旗舰店,5,448721,14020

In [20]:
total_df.columns

Index(['Unnamed: 0', 'middle_clss', 'month', 'senior_name', 'shop_link', '全选',
       '地域', '掌柜名', '排名', '销售额', '销量'],
      dtype='object')

In [21]:
total_df2 = total_df[['senior_name', 'middle_clss', 'month', 'shop_link', '地域', '掌柜名', '排名',  '销量', '销售额']].copy()

In [22]:
total_df2.head()

,senior_name,middle_clss,month,shop_link,地域,掌柜名,排名,销量,销售额
0,内衣家居服,乳贴,201803,http://shop112068244.taobao.com/,"辽宁省, 锦州市",柯恩纳旗舰店,1,47117,1891576
1,内衣家居服,乳贴,201803,http://shop191214021.taobao.com/,NaN,斯米莱旗舰店,2,34911,1314520
2,内衣家居服,乳贴,201803,http://shop66862794.taobao.com/,"浙江, 杭州",艾丝朵秀旗舰店,3,21189,272175
3,内衣家居服,乳贴,201803,http://shop110998652.taobao.com/,"湖北省, 武汉市",安黛拉旗舰店,4,14688,607402
4,内衣家居服,乳贴,201803,http://shop69194068.taobao.com/,上海,jeeanjoose旗舰店,5,14020,448721

In [23]:
excel_writer = pd.ExcelWriter('{}\行业各中类靠前的店铺清单--至1909.xlsx'.format(base_dir.parent.parent), engine='xlsxwriter', options={'strings_to_urls': False})
total_df2.to_excel(excel_writer)
excel_writer.close()